# Chapter 4 NumPy Basics: Array and Vectorized Computation

#### Note
1. Numpy internally stores data in c contiguous block of memory, independent of other built-in Python objects. Numpy arrays also use much less memory than built-in Python sequences.
2. Numpy operations perform complex computations on entire arrays without the need for Python for loops.
3. Numpy is faster than regular Python code because its C-based algorithms avoid overhead present with regular interpreted Python code.

In [ ]:
import numpy as np
import sys

In [ ]:
my_arr = np.arange(1_000_000)
my_list = list(range(1_000_000))

In [ ]:
%timeit my_arr2 = my_arr * 2

673 µs ± 16.2 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [ ]:
%timeit my_list2 = [x * 2 for x in my_list]

23.1 ms ± 238 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


## 4.1 The Numpy ndarray: A Multidimensional Array Object

In [ ]:
data = np.array([[1.5, -0.1, 3], [0, -3, 6.5]])
data

array([[ 1.5, -0.1,  3. ],
       [ 0. , -3. ,  6.5]])

In [ ]:
data * 10

array([[ 15.,  -1.,  30.],
       [  0., -30.,  65.]])

In [ ]:
data + data

array([[ 3. , -0.2,  6. ],
       [ 0. , -6. , 13. ]])

In [ ]:
data.shape

(2, 3)

In [ ]:
# All of the elements in an ndarray must have the same type
data.dtype

dtype('float64')

### Creating ndarrays

In [ ]:
data1 = [6, 6.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 6.5, 8. , 0. , 1. ])

In [ ]:
arr1.dtype

dtype('float64')

In [ ]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
arr2.dtype

dtype('int64')

In [ ]:
print(arr1.ndim)
print(arr2.ndim)

1
2


In [ ]:
zero_arr = np.zeros(10)
zero_arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
one_arr = np.ones((3, 4))
one_arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
empty_arr = np.empty((2, 3, 2))
empty_arr

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [ ]:
# numpy.arange is an array-valued version of the built-in Python range function
arr3 = np.arange(10)
print(arr3)
print(type(arr3))

arr4 = range(10)
print(arr4)
print(type(arr4))

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
range(0, 10)
<class 'range'>


### Data Types for ndarrays

In [ ]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int8)
print(arr1.dtype)
print(arr2.dtype)
print(sys.getsizeof(arr1))
print(sys.getsizeof(arr2))

float64
int8
136
115


In [ ]:
int_array = np.arange(10)
calibers = np.array([.22, .27, .440, .50], dtype=np.float64)

In [ ]:
print(int_array)
print(int_array.dtype)

[0 1 2 3 4 5 6 7 8 9]
int64


In [ ]:
int_array = int_array.astype(calibers.dtype)
print(int_array)
print(int_array.dtype)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
float64


In [ ]:
numeric_strings = np.array(["-1", "-2.0", "0.99"])
numeric_strings

array(['-1', '-2.0', '0.99'], dtype='<U4')

In [ ]:
numeric_strings.astype(np.float64)

array([-1.  , -2.  ,  0.99])

### Arithmetic with Numpy Arrays

Any arithmetic operations between equal-size arrays apply the operation element-wist.

In [ ]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])

In [ ]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [ ]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

Arithmetic operations with scalars propagate the scalar argument to each element in the array

In [ ]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [ ]:
arr ** 2

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [ ]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

### Basic Indexing and Slicing

In [ ]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr[5]

5

In [ ]:
arr[5:8]

array([5, 6, 7])

In [ ]:
# A slice of numpy array is the view of the array, which is not a copy
# of part of the array. That means any modifications to the view will be
# reflected on the original array.

arr[5:8] = 12
print(arr)

x = arr[5:8]
x[:] = 14
print(arr)

[ 0  1  2  3  4 12 12 12  8  9]
[ 0  1  2  3  4 14 14 14  8  9]


In [ ]:
list1 = [0, 1, 2, 3, 4, 5, 6]

# if we want to assign 12 to the third and forth elements in list1
# we cannot write as list1[2:4] = 12, the right hand side must be a list
# has the same length as the left list slice
list1[2:4] = [12, 12]
print(list1)

y = list1[2:4]
print(y)
for i in range(0, len(y)):
    y[i] = -1

print(y)
print(list1)

[0, 1, 12, 12, 4, 5, 6]
[12, 12]
[-1, -1]
[0, 1, 12, 12, 4, 5, 6]


For a multi-dimensions array, we can access it through any of its axises

In [ ]:
data = np.array([[4, 7], [0, 2], [-5, 6], [0, 0], [1, 2]])

In [ ]:
# Indexing by axis 0 (row)
data[0]

array([4, 7])

In [ ]:
# Indexing by axis 1 (column)
data[:, 1]

array([7, 2, 6, 0, 2])

In [ ]:
data[0:2, 1]

array([7, 2])

In [ ]:
# Indexing by all axises
print(data[1, 1])

# The indexing can be discrete
# For example we can the second column in the first and forth row
# The discrete index belong to one axis should be in a list
print(data[[0, 3], 1])

# Access the first column of the first row and the second column of the third row
print(data[[0, 2], [0, 1]])

2
[7 0]
[4 6]


### Boolean Indexing

In [ ]:
data = np.array([[4, 7], [0, 2], [-5, 6], [0, 0], [1, 2]])
names = np.array(["Bob", "Joe", "Will", "Bob", "Will"])

data[[1, 2], [0, 1]]

array([0, 6])

In [ ]:
names == "Bob"

array([ True, False, False,  True, False])

In [ ]:
print(names != "Bob")
# negate operator
print(~(names == "Bob"))

[False  True  True False  True]
[False  True  True False  True]


In [ ]:
data[names == "Bob"]

array([[4, 7],
       [0, 0]])

In [ ]:
data[names != "Bob"]

array([[ 0,  2],
       [-5,  6],
       [ 1,  2]])

In [ ]:
data[~(names == "Bob")]

array([[ 0,  2],
       [-5,  6],
       [ 1,  2]])

In [ ]:
cond = names == "Bob"
data[~cond]

array([[ 0,  2],
       [-5,  6],
       [ 1,  2]])

In [ ]:
# & (and operator) and | (or operator)
cond = (names == "Bob") | (names == "Joe")
print(data[cond])

array([[4, 7],
       [0, 2],
       [0, 0]])

In [ ]:
print(data < 0)
data[data < 0] = 0
print(data)

[[False False]
 [False False]
 [False False]
 [False False]
 [False False]]
[[4 7]
 [0 2]
 [0 6]
 [0 0]
 [1 2]]


### Fancy Indexing

In [ ]:
arr = np.zeros((8, 4))
print(arr)
